### ISSUE TITLE
Update to use <time> element 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-datetime#11]
## Is your feature request related to a problem? Please describe.

The current version of this element places the date/time into a `<span>` element. 

## Describe the solution you'd like

This element should be updated to support the `<time>` element. 

> This element is for presenting dates and times in a machine readable format. For example, this can help a user agent offer to add an event to a user's calendar.

> This element should not be used for dates prior to the introduction of the Gregorian calendar (due to complications in calculating those dates).

> The datetime value (the machine-readable value of the datetime) is the value of the element's datetime attribute, which must be in the proper format (see below). If the element does not have a datetime attribute, it must not have any element descendants, and the datetime value is the element's child text content.

The `<time>` element does nothing to support screen readers or conversion. The role of this element is to provide context to the browser for other features that used to be supported by micro-formats. E.g. adding a date to a user's calendar.

**Comment by blackfalcon** [comment]
Easier said than done. For the scope of this update, the `dateTime` HTML attribute of the `time` element requires a [specific return of data](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time#valid_datetime_values).

To support this feature, an additional switch statement along the lines of the `whichDate()` feature.

**Comment by blackfalcon** [comment]
It should also be noted that auro-flight wraps auro-datetime in a `time` element. 

https://github.com/AlaskaAirlines/auro-flight/blob/50854e9213f571c6137303fa466a7ea9a3df944a/src/auro-flight-main.js#L156-L158

**Comment by Patrick-Daly-AA** [comment]
Closing as will not do.
